//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskComment
    {
        public int CommentId { get; set; }
        public int TaskId { get; set; }
        public string Comment { get; set; }
        public System.DateTime AddedDateTime { get; set; }
        public int CreatedUserId { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
